# Generated by Django 4.2.5 on 2023-10-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
