# Generated by Django 4.2.5 on 2023-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_subject_options_alter_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
    ]
