# Generated by Django 4.2.5 on 2023-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='material',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
